### ISSUE TITLE
请问在哪里启用双拼

### ISSUE THREAD

**Issue by 6486449j** [Towdium/JustEnoughCharacters#58]
如题

翻了一圈配置文件，没找到相关的选项

**Comment by Towdium** [comment]
keyboard 里面可以配小鹤、自然码

**Comment by 6486449j** [comment]
> keyboard 里面可以配小鹤、自然码

我没搞懂您的意思，到底是哪一处的 keyboard 呢

**Comment by Towdium** [comment]
打开配置文件`jecharacters.toml`
默认内容应该是这样的：
```toml
[General]
	#Set to true to enable fuzzy spelling zh <=> z
	enableFZh2z = false
	#Set to true to enable fuzzy spelling eng <=> en
	enableFEng2en = false
	#Set to true to enable fuzzy spelling ch <=> c
	enableFCh2c = false
	#Set to true to enable fuzzy spelling ang <=> an
	enableFAng2an = false
	#Keyboard for the checker to use
	#Allowed Values: QUANPIN, DAQIAN, XIAOHE, ZIRANMA
	enumKeyboard = "QUANPIN"
	#Set to true to enable fuzzy spelling u <=> v
	enableFU2v = false
	#Set to true to disable JEI's split for search tokens
	enableQuote = false
	#Set to false to disable chat message when entering world
	enableChat = false
	#Set to true to enable fuzzy spelling ing <=> in
	enableFIng2in = false
	#Set to true to enable fuzzy spelling sh <=> s
	enableFSh2s = false

[Utilities]
	#List of classes to dump all the functions
	listDumpClass = []
	#Set true to print verbose debug message
	enableVerbose = false
```
把这个`enumKeyboard `改一下就行了
